const express = require('express')
const hbs = require('hbs')
const parser = require('body-parser')
const mongoose = require('mongoose')
const methodOverride = require('method-override')
const passport = require('passport')
const router = express.Router()
